### ISSUE TITLE
Jenkins update via jenkins-cli.jar fails

### ISSUE THREAD

**Issue by xando** [Linaro/art-reports#16]
```
[2016-03-31 08:42:01,157] INFO: Received task: benchmarks.tasks.set_testjob_results[c450b422-be65-4752-8ca2-d2ce919d7af1]
No such file exists: K6GnZPf2WZm3
Jenkins CLI
Usage: java -jar jenkins-cli.jar [-s URL] command [opts...] args...
Options:
-s URL       : the server URL (defaults to the JENKINS_URL env var)
-i KEY       : SSH private key file used for authentication
-p HOST:PORT : HTTP proxy host and port for HTTPS proxy tunneling. See http://jenkins-ci.org/https-proxy-tunnel
-noCertificateCheck : bypass HTTPS certificate check entirely. Use with caution
-noKeyAuth   : dont try to load the SSH authentication private key. Conflicts with -i

The available commands depend on the server. Run the help command to
see the list.
[2016-03-31 08:42:01,283] ERROR: Task benchmarks.tasks.update_jenkins[7f9b72d5-5732-46be-abeb-4331a48ec912] raised unexpected: CalledProcessError()
Traceback (most recent call last):
  File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/art-reports.linaro.org/project/benchmarks/tasks.py", line 151, in update_jenkins
    description,
  File "/srv/art-reports.linaro.org/project/benchmarks/tasks.py", line 166, in jenkins_client_call
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError
```

**Comment by xando** [comment]
fixed
