### ISSUE TITLE
Handle 404 when jenkins updates via jar

### ISSUE THREAD

**Issue by xando** [Linaro/art-reports#17]
The Jenkins results are removed after some time, so it happens that we still try to update the jenkins build, but the build won't be accessible

```
java -jar /srv/staging-art-reports.linaro.org/project/benchmarks/jenkins-cli.jar -s https://android-build.linaro.org/jenkins -i /srv/staging-art-reports.linaro.org/ext/art-reports-bot.key set-build-description linaro-art-tip-build-nexus9-MicroBenchmarks-Baseline 226 "test"
java.lang.NullPointerException
	at hudson.cli.SetBuildDescriptionCommand.run(SetBuildDescriptionCommand.java:31)
	at hudson.cli.CLICommand.main(CLICommand.java:237)
	at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
	at sun.reflect.GeneratedMethodAccessor11718.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:608)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:583)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:542)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
	at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
	at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

The previous version of the update had as safety mechanism to avoid things like that https://github.com/Linaro/art-reports/blob/51dae27d56fd5290b50605f452c797577d02e171/benchmarks/tasks.py#L182

Would be good to have something similar now when jar is in place.

**Comment by terceiro** [comment]
argh :-(

I'm on it
