### ISSUE TITLE
jenkins update action fails after jenkins upgrade

### ISSUE THREAD

**Issue by mwasilew** [Linaro/art-reports#20]
It seems that after jenkins upgrade last weekend the action to update jenkins build desctiption fails. Example failure below:

> Task benchmarks.tasks.update_jenkins with id 55005ef7-398f-4622-aba9-dfcc12b753d4 raised exception:
> 'CalledProcessError()'
> 
> 
> Task was called with args: [<Result: 469 - https://android-build.linaro.org/jenkins/job/linaro-art-tip-build-nexus5x-MicroBenchmarks-Baseline/197/>] kwargs: {}.
> 
> The contents of the full traceback was:
> 
> Traceback (most recent call last):
>   File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/srv/art-reports.linaro.org/project/benchmarks/tasks.py", line 151, in update_jenkins
>     description,
>   File "/srv/art-reports.linaro.org/project/benchmarks/tasks.py", line 166, in jenkins_client_call
>     subprocess.check_call(cmd)
>   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command '['java', '-jar', '/srv/art-reports.linaro.org/project/benchmarks/jenkins-cli.jar', '-s', 'https://android-build.linaro.org/jenkins', '-i', '/srv/art-reports.linaro.org/ext/art-reports-bot.key', 'set-build-description', u'linaro-art-tip-build-nexus5x-MicroBenchmarks-Baseline', '197', u'<a href="/#/build/469">Details</a><br/>\n\nLAVA <a href="https://validation.linaro.org/scheduler/job/806323.1">806323.1</a> -<img class="icon-sm" src="/jenkins/static/art-reports/images/16x16/clock.png" alt="Submitted" tooltip="Submitted"><br/>\n\nLAVA <a href="https://validation.linaro.org/scheduler/job/806323.0">806323.0</a> -<img class="icon-sm" src="/jenkins/static/art-reports/images/16x16/clock.png" alt="Submitted" tooltip="Submitted"><br/>\n\nLAVA <a href="https://validation.linaro.org/scheduler/job/806325.1">806325.1</a> -<img class="icon-sm" src="/jenkins/static/art-reports/images/16x16/clock.png" alt="Submitted" tooltip="Submitted"><br/>\n\nLAVA <a href="https://val
>  idation.linaro.org/scheduler/job/806325.0">806325.0</a> -<img class="icon-sm" src="/jenkins/static/art-reports/images/16x16/clock.png" alt="Submitted" tooltip="Submitted"><br/>\n\nLAVA <a href="https://validation.linaro.org/scheduler/job/806327.1">806327.1</a> -<img class="icon-sm" src="/jenkins/static/art-reports/images/16x16/clock.png" alt="Submitted" tooltip="Submitted"><br/>\n\nLAVA <a href="https://validation.linaro.org/scheduler/job/806327.0">806327.0</a> -<img class="icon-sm" src="/jenkins/static/art-reports/images/16x16/clock.png" alt="Submitted" tooltip="Submitted"><br/>\n\nLAVA <a href="https://validation.linaro.org/scheduler/job/806329.1">806329.1</a> -<img class="icon-sm" src="/jenkins/static/art-reports/images/16x16/clock.png" alt="Submitted" tooltip="Submitted"><br/>\n\nLAVA <a href="https://validation.linaro.org/scheduler/job/806329.0">806329.0</a> -<img class="icon-sm" src="/jenkins/static/art-reports/images/16x16/clock.png" alt="Submitted" tooltip="Submitted">\n\n\n
>  ']' returned non-zero exit status 255

**Comment by terceiro** [comment]
cannot reproduce this locally, or on the server. I even retried manually calling the `update_jenkins` task with this very `Result` object as parameters, and it worked ok. I suspect this is an issue on the jenkins side. I will make it display the command output in the exception
