### ISSUE TITLE
LAVA job fetching fails with strange error

### ISSUE THREAD

**Issue by mwasilew** [Linaro/art-reports#33]
Despite updating the code, restarting all services (including RabbitMQ) and clearing queue from old jobs, the error still happens. I also removed all .pyc files just in case. Traceback below:

    [2016-04-21 08:56:14,185] ERROR: Task benchmarks.tasks.set_testjob_results[49d54de1-1b1b-4dea-acfa-a264e069fba3] raised unexpected: AttributeError("'TestJob' object has no attribute 'results_loaded'",)
    Traceback (most recent call last):
      File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
        R = retval = fun(*args, **kwargs)
      File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
        return self.run(*args, **kwargs)
      File "/srv/art-reports.linaro.org/project/benchmarks/tasks.py", line 29, in set_testjob_results
        store_testjob_data(testjob, test_results)
      File "/srv/art-reports.linaro.org/project/benchmarks/tasks.py", line 39, in store_testjob_data
        testjob.save()
      File "/srv/art-reports.linaro.org/project/benchmarks/models.py", line 233, in save
        super(TestJob, self).save(*args, **kwargs)
      File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
        force_update=force_update, update_fields=update_fields)
      File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
        updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
      File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in _save_table
        for f in non_pks]
      File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 684, in pre_save
        return getattr(model_instance, self.attname)
    AttributeError: 'TestJob' object has no attribute 'results_loaded'

**Comment by mwasilew** [comment]
It appears some 'old' serialized objects were still present in celery's cache. Clearing these objects solved the issue:

    from celery.task.control import discard_all
    discard_all()

**Comment by mwasilew** [comment]
I'm reopening this as the error emails are back. No idea what caused the problem as there were no changes made.

**Comment by mwasilew** [comment]
No longer reproducible after cleaning the queue and pulling new code. Closing.
