### ISSUE TITLE
gerrit update fails with "Argument list too long" error

### ISSUE THREAD

**Issue by terceiro** [Linaro/art-reports#39]
```
Gerrit update failed
Traceback (most recent call last):
  File "/srv/art-reports.linaro.org/project/benchmarks/gerrit.py", line 62, in update
    method(result, message)
  File "/srv/art-reports.linaro.org/project/benchmarks/gerrit.py", line 48, in ssh
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long

Request repr(): unavailable
```

**Comment by mwasilew** [comment]
I think it's fixed now. I didn't see it for some time
