### ISSUE TITLE
email sending fails when using compare.py

### ISSUE THREAD

**Issue by mwasilew** [Linaro/art-reports#57]
Trace below:

Task benchmarks.tasks.report_email with id 15099103-d819-4773-9c26-e91f1226cdb2 raised exception:
'CalledProcessError()'

    Task was called with args: [<Result: 987 - https://android-build.linaro.org/jenkins/job/linaro-art-tip-build-nexus5x-MicroBenchmarks/190/>] kwargs: {}.

    The contents of the full traceback was:

    Traceback (most recent call last):
      File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
        R = retval = fun(*args, **kwargs)
      File "/srv/art-reports.linaro.org/.virtualenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
        return self.run(*args, **kwargs)
      File "/srv/art-reports.linaro.org/project/benchmarks/tasks.py", line 267, in report_email
        return mail.result_progress(current, current.baseline)
      File "/srv/art-reports.linaro.org/project/benchmarks/mail.py", line 13, in result_progress
        comparison=render_comparison(baseline.data.all(), current.data.all()),
      File "/srv/art-reports.linaro.org/project/benchmarks/comparison.py", line 17, in render_comparison
        os.path.join(tmpdir, "after.json"),
      File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    CalledProcessError: Command '['/srv/art-reports.linaro.org/ext/art-testing/compare.py', '/tmp/tmpTITTF9/before.json', '/tmp/tmpTITTF9/after.json']' returned non-zero exit status 1

**Comment by mwasilew** [comment]
This is fixed now
